### ISSUE TITLE
POST ~/team-boost/purchase 出错，可能腾讯已经修复了战斗福利的问题

### ISSUE THREAD

**Issue by ryuujo1573** [XHXIAIEIN/LeagueCustomLobby#1]
{
    "errorCode": "RPC_ERROR",
    "httpStatus": 500,
    "implementationDetails": {},
    "message": "Error response for POST /lol-lobby-team-builder/champ-select/v1/team-boost/purchase: Unable to purchase team boost: Received status Error: INVALID_STATE instead of expected status of OK from request to teambuilder-draft:activateBattleBoostV1"
}

**Comment by XHXIAIEIN** [comment]
是的，此接口在 2021/02/18 14:00 被腾讯官方紧急修复。
