### ISSUE TITLE
在pycharm运行报错

### ISSUE THREAD

**Issue by willinglisten** [XHXIAIEIN/LeagueCustomLobby#10]
TypeError: ssl should be SSLContext, bool, Fingerprint or None, got False instead.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002142D7D6340>

**Comment by XHXIAIEIN** [comment]
不清楚，我没有用 pycharm，你可以找找 pycharm 相关的设置。或者试试 vscode，也可以直接双击打开 .py 用 python IDLE 运行。
