### ISSUE TITLE
/lol-lobby/v2/lobby/members 接口有不用库，自己调用 request 实现的吗？

### ISSUE THREAD

**Issue by renren123** [XHXIAIEIN/LeagueCustomLobby#11]
/lol-lobby/v2/lobby/members 接口有不用库自己调用 request 实现的吗？

这个接口我一直调不通，在 git bash 上可以访问，但是在代码和cmd上返回错误，
git bash:
![image](https://user-images.githubusercontent.com/26969703/155883841-a2eb337f-d165-41d6-af3f-560f28f54248.png)

cmd:
![image](https://user-images.githubusercontent.com/26969703/155883379-80488d73-3ccc-48db-b915-aa4ca03dd836.png)

用代码和postman 访问 这个接口 和 cmd 报错一样，不知道是不是 ssl 的问题

**Comment by XHXIAIEIN** [comment]
是的，你不能直接在上面用 curl 或者 Invoke-RestMethod
