### ISSUE TITLE
api 调不通

### ISSUE THREAD

**Issue by Dobedoooo** [XHXIAIEIN/LeagueCustomLobby#12]
为什么有的接口用工具或者代码调返回 errorCode，但是用浏览器可以返回正常数据呢？
比如`/lol-mactch-history/v3/matchlist/account/{accountId}` 还有接受对局的接口，卡了好几天了。
但是网上其他对局工具就能调通，救救我吧😭

**Comment by XHXIAIEIN** [comment]
据说最近官方已经将 lockfile 文件移除，不再提供API密钥了。

你可以参考这篇文章，从 LeagueClientUx.exe 游戏进程里面获取 token 和 port 这些信息。
https://hextechdocs.dev/getting-started-with-the-lcu-api/#the-process-list-method

**Comment by Dobedoooo** [comment]
> 据说最近官方已经将 lockfile 文件移除，不再提供API密钥了。
> 
> 你可以参考这篇文章，从 LeagueClientUx.exe 游戏进程里面获取 token 和 port 这些信息。 https://hextechdocs.dev/getting-started-with-the-lcu-api/#the-process-list-method

抱歉，例如`/lol-match-history/v3/matchlist/account/{accountId}` 这个接口，用 node 访问：
```
import request from 'request';

process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

const url = 'https://riot:KaM2WJSZ9SXAdxY6kOJgcQ@127.0.0.1:58388/lol-match-history/v3/matchlist/account/2965465990';

request(url, (err, res, body) => {
    console.log(body);
})
```
结果为：
`{"errorCode":"RESOURCE_NOT_FOUND","httpStatus":404,"message":"Invalid function"}`
但是用浏览器访问该 url，结果为：
![uTools_1646374076576](https://user-images.githubusercontent.com/57029169/156709297-454e980f-c69f-4fb7-be1d-feda21c421c7.png)

**Comment by XHXIAIEIN** [comment]
目前 LCU-API 关于 match-history 相关的接口都用不了，官方那边最近又在升级 match-v5 的 API，他们估计是先把客户端这边的接口屏蔽了，看看后面的结果先。

**Comment by Dobedoooo** [comment]
好的，了解了

**Comment by Dobedoooo** [comment]
解决了，用h2协议来调就好了

**Comment by sea72** [comment]
4月20日，/lol-match-history/v3/matchlist/account/{accountId}这个api用h2似乎也无法调用了
