### ISSUE TITLE
请问访问localhost的username和password是什么？在哪里获取

### ISSUE THREAD

**Issue by 10cks** [XHXIAIEIN/LeagueCustomLobby#13]
![image](https://user-images.githubusercontent.com/47177550/157406186-34f4c10c-15e0-4d3e-9070-79a860e04a02.png)
如图，没有找到对应信息。

**Comment by XHXIAIEIN** [comment]
最近官方已经将 lockfile 文件移除了，不再提供API密钥。

你可以参考这篇文章，从 LeagueClientUx.exe 游戏进程里面获取 token 和 port 这些信息。
https://hextechdocs.dev/getting-started-with-the-lcu-api/#the-process-list-method

**Comment by 10cks** [comment]
好的，十分感谢
