### ISSUE TITLE
为什么最近查不了历史战绩了

### ISSUE THREAD

**Issue by Dobedoooo** [XHXIAIEIN/LeagueCustomLobby#15]
```/lol-match-history/v3/matchlist/account``` 返回了 404，之前还可以正常使用，请问您有遇到这个问题吗

**Comment by tabqw** [comment]
lol-match-history/v1/products/lol/current-summoner/matches
这个好像能查

**Comment by tabqw** [comment]
> `/lol-match-history/v3/matchlist/account` 返回了 404，之前还可以正常使用，请问您有遇到这个问题吗

lol-match-history/v1/products/lol/current-summoner/matches这个能查自己的

**Comment by XilyFeAAAA** [comment]
> `/lol-match-history/v3/matchlist/account` 返回了 404，之前还可以正常使用，请问您有遇到这个问题吗

报错404的都是需要用http2

**Comment by XHXIAIEIN** [comment]
查自己的：
```
/lol-match-history/v1/products/lol/current-summoner/matches?begIndex=0&endIndex=9
```

查别人的：
```
/lol-match-history/v1/products/lol/{puuid}/matches
```
