### ISSUE TITLE
监听事件有回调函数吗？

### ISSUE THREAD

**Issue by httpsColon** [XHXIAIEIN/LeagueCustomLobby#16]
https://github.com/XHXIAIEIN/LeagueCustomLobby/wiki/lol-lobby#%E7%9B%91%E5%90%AC%E4%BA%8B%E4%BB%B6

不懂其他语言怎么创建监听

**Comment by XHXIAIEIN** [comment]
工作原理是 WebSocket ，其他语言应该也会有，连接到对应的事件端口即可。
