### ISSUE TITLE
请教监听客户端状态

### ISSUE THREAD

**Issue by tabqw** [XHXIAIEIN/LeagueCustomLobby#19]
你好，请问实时监测客户端状态比如房间创建、选择英雄、进入游戏等，是如何实现的？贴的py代码看得不是很懂

**Comment by XHXIAIEIN** [comment]
需要先了解一些关于 websocket 的基础知识，可以看看这篇文章《LCU websocket 入门》(https://hextechdocs.dev/getting-started-with-the-lcu-websocket/)

这个项目里用的是 [lcu-driver](https://github.com/sousa-andre/lcu-driver) 或者 [Willump](https://github.com/elliejs/Willump) 它已经内置了 websockets 事件连接器，在使用的时候只需要订阅相关端口事件就可以了。例如在你房间创建的时候，客户端会向这个端口返回请求数据，我们通过 websockets 去监听这个端口事件，就可以知道它的状态了。

**Comment by tabqw** [comment]
好的，十分感谢🙂
