### ISSUE TITLE
直接创建游戏大厅的用法

### ISSUE THREAD

**Issue by f12345678900** [XHXIAIEIN/LeagueCustomLobby#2]
直接创建房间的使用方法?
抱歉麻烦你了

**Comment by XHXIAIEIN** [comment]
建议将 [README.md](https://github.com/XHXIAIEIN/LeagueCustomLobby/blob/main/README.md#%E7%9B%B4%E6%8E%A5%E5%88%9B%E5%BB%BA%E6%88%BF%E9%97%B4) 的说明阅读一遍。

只需要传入一个 `queueId` 的参数。你在客户端看到有什么模式，才能传入它对应的  `queueId` ，当前版本可用的模式列表在[README.md](https://github.com/XHXIAIEIN/LeagueCustomLobby/blob/main/README.md#queue-maps-game-modes-game-types) 中可以找到。
