### ISSUE TITLE
请问怎么获取当前大区信息呢？

### ISSUE THREAD

**Issue by LvBay** [XHXIAIEIN/LeagueCustomLobby#20]
比如当前是艾欧尼亚还是黑色玫瑰

**Comment by XHXIAIEIN** [comment]
lcuapi里面没有国服分区的接口(可能有，但只有开发组内部才知道)

国服似乎有自己的一套API，如果你在国服官网研究一下控制台信息能发现，但也仅对内部使用的。

现有的第三方工具好像也没有直接获取分区的功能，包括官方的活动网站都是让你自己先选分区，然后再绑定角色。
