### ISSUE TITLE
想知道如何去除浮空窗口 比如直接返回主页

### ISSUE THREAD

**Issue by eimyliya** [XHXIAIEIN/LeagueCustomLobby#21]
![image](https://github.com/XHXIAIEIN/LeagueCustomLobby/assets/112249180/8b5eefe6-e36f-4d84-9fa7-a87f998322c6)
找了一圈没找到，大佬知道吗

以及有api购买英雄吗  store的api都试了一下 都不行

**Comment by XHXIAIEIN** [comment]
store 的部分的 api 主要用来查询商城列表的吧，不能代替用户操作去直接购买东西才是正常、最合理的。要是人人都能通过一行代码跳过用户直接购买东西，拿来做整蛊程序那场面光是想想就可怕。。如果你一定需要用这些权限，你得联系 Riot 单独申请。

作为第三方工具，不建议去碰商城的API。首先是没啥义务帮tx卖东西。其次国服自己有道聚城，他们有自己的一套API在里面。
