### ISSUE TITLE
你好，有关于云顶之奕的api资料么~

### ISSUE THREAD

**Issue by 0lizi** [XHXIAIEIN/LeagueCustomLobby#3]

**Comment by XHXIAIEIN** [comment]
你可以看拳头开发者页面的云顶之弈专栏 TEAMFIGHT TACTICS https://developer.riotgames.com/docs/tft 从这里下载游戏中的静态数据。或者 communitydragon 里面也有收录 tft 的数据：http://raw.communitydragon.org/latest/cdragon/tft/ 

其实腾讯已经做了一个不错的云顶之弈站点 https://lol.qq.com/tft/#/index 可以参考一下。


顺便一提：
如果你要开发 TFT 的第三方工具，必须跟RIOT申请授权，否则不允许提供给玩家使用，也不允许使用云顶之弈的商标。
https://www.riotgames.com/en/DevRel/teamfight-tactics

**Comment by 0lizi** [comment]
谢谢哥们的热心回复，静态数据我昨天也下载下来了，我想或与一些云顶模式下的实时游戏数据，比如说角色的卡牌，就类似5v5匹配模式那样能拿到英雄击杀数，天赋，装备这样的数据。

**Comment by XHXIAIEIN** [comment]
> 谢谢哥们的热心回复，静态数据我昨天也下载下来了，我想或与一些云顶模式下的实时游戏数据，比如说角色的卡牌，就类似5v5匹配模式那样能拿到英雄击杀数，天赋，装备这样的数据。

目前官方还没有开放实时数据的接口，据说以后会开放，但是时间不确定。也许哪天看到掌盟上线这个功能，就说明拳头开放了API，到时候再去瞧瞧。

**Comment by 0lizi** [comment]
我意思是实时的数据，比如5-2阶段，什么羁绊，几张卡牌，几费卡，5-4阶段又如何这样的数据，就像5v5模式谁击杀了谁这样的数据，你指的数据手机掌盟已经可以查看了~
