### ISSUE TITLE
你有找到商城的api吗

### ISSUE THREAD

**Issue by yqhyam** [XHXIAIEIN/LeagueCustomLobby#4]
导入postman试了半天没找到商城的相关api..

**Comment by XHXIAIEIN** [comment]
你可以到[lcu-schema](http://www.mingweisamuel.com/lcu-schema/tool/#/) 找关于 [lol-store](http://www.mingweisamuel.com/lcu-schema/tool/#/Plugin%20lol-store) 的部分。例如 ` ​/lol-store​/v1​/catalog ` 就是获得商店在售的列表清单。

顺便多嘴一句，不建议去碰商城的API。首先是没啥义务帮tx卖东西。其次官方有个道聚城的网站专门负责国服的商城，似乎他们也有自己的一套API在里面。另外，作为第三方工具，涉及游戏内支付相关的东西本身就很奇怪，用户不可能在你这边进行交易。
