### ISSUE TITLE
数据分析建模可视化

### ISSUE THREAD

**Issue by rainzee** [XHXIAIEIN/LeagueCustomLobby#5]
您好，我目前是青训的数据分析师，请问如何取得联系，我想通过该Api对选手的数据进行量化，追踪和建模分析

**Comment by XHXIAIEIN** [comment]
游戏实时数据，可以参考Riot开发者文档：
https://developer.riotgames.com/docs/lol#game-client-api_live-client-data-api

我的 Wiki 里面也有一部分笔记，查询选手各方面的得分：
https://github.com/XHXIAIEIN/LeagueCustomLobby/wiki/client:--game-client

**Comment by rainzee** [comment]
请问怎么联系

**Comment by XHXIAIEIN** [comment]
> 请问怎么联系

QQ: 271028354
