### ISSUE TITLE
请问一下PlatformDisabled改成Available是在哪里改，我找到的queues.json里面木有

### ISSUE THREAD

**Issue by ice-seal** [XHXIAIEIN/LeagueCustomLobby#8]
如题
[](url)
![QQ截图20211103162037](https://user-images.githubusercontent.com/28422863/140028062-b9c36f5d-fabf-4b3c-88db-c6d237f9981a.png)

**Comment by XHXIAIEIN** [comment]
如 #6，我没有实际去尝试过解包本地文件。其实现在LOL轮换模式不断在持续上线，没啥必要把老模式翻出来自娱自乐了~
