### ISSUE TITLE
获取成就点

### ISSUE THREAD

**Issue by QiuYe5** [XHXIAIEIN/LeagueCustomLobby#9]
你好，请问下如何通过客户端获取自己每个英雄的成就点呢？我通过 “/lol-champions/v1/owned-champion-minimal”的方式没有读取到相关信息

**Comment by XHXIAIEIN** [comment]
**GET**
```
/lol-collections/v1/inventories/{summonerId}/champion-mastery
```

**Comment by QiuYe5** [comment]
好的 多谢 我试一下

**Comment by XHXIAIEIN** [comment]
不好意思，我看错了。英雄的成就点数应该是在 [lol-collections](http://www.mingweisamuel.com/lcu-schema/tool/#/Plugin%20lol-collections) 位置。  
  
你可以用这个来获取每个英雄的成就点
```
/lol-collections/v1/inventories/{summonerId}/champion-mastery
```
